// Generated by CoffeeScript 1.4.0

App.PagesPageController.reopen({
  projects: [
    {
      title: "Mobile Distribution System",
      uri: "http://mobile-distribution-system.appspot.com"
    }, {
      title: "Kampoze",
      uri: "http://kampoze.appspot.com"
    }, {
      title: "Todos",
      uri: "http://todosmvc.appspot.com/"
    }, {
      title: "Exxaro Ventures",
      uri: "kelonye.github.com/travel-out/exxaroventures/"
    }, {
      title: "Travel Out",
      uri: "kelonye.github.com/travel-out/"
    }
  ],
  team: [
    {
      name: "Alex Ondieki",
      email: "alexnyaswabu@gmail.com",
      role: "Director"
    }, {
      name: "Mitchel Kelonye",
      email: "kelonyemitchel@gmail.com",
      role: "Web Developer"
    }, {
      name: "Oluoch Ebrahim",
      email: "oluochebrahim@gmail.com",
      role: "Web Developer"
    }, {
      name: "Daniel Ragira",
      email: "danielragira",
      role: "Sales Manager"
    }
  ],
  init: function() {
    var that;
    that = this;
    return Em.$.getJSON("http://search.twitter.com/search.json?q=kelonye&page=1&callback=?", function(data) {
      var tweets;
      tweets = data.results.map(function(content) {
        content.uri = "https://twitter.com/twitterapi/status/" + content.id_str;
        return content;
      });
      return that.set("tweets", tweets);
    });
  }
});
