// Generated by CoffeeScript 1.4.0
var compile, get, set;

get = Em.get;

set = Em.set;

compile = Em.Handlebars.compile;

App.PAGES.forEach(function(page) {
  return Em.TEMPLATES[page] = compile(require("./templates/pages/" + page));
});

Em.TEMPLATES['pages'] = compile(require('./templates/index'));

App.NavItem = Em.View.extend(require('ember-select'), {
  template: compile(require('./templates/page-list-item')),
  title: Em.computed(function() {
    var content;
    content = get(this, 'content');
    return content.replace(/-/g, ' ');
  })
});

App.Nav = Em.CollectionView.extend({
  tagName: "ul",
  classNames: ["nav"],
  itemViewClass: App.NavItem
});

App.TeamMemberView = Em.View.extend({
  tagName: "a",
  rel: "tooltip",
  href: (function() {
    var email;
    email = get(this, 'content.email');
    return "mailto:" + email;
  }).property("content.email"),
  img: (function() {
    var name;
    name = get(this, "content.name");
    name = name.replace(/\s/g, "_").toLowerCase();
    return "build/client/img/team/" + name + ".png";
  }).property("content.name"),
  attributeBindings: ["rel", "href"],
  template: Em.Handlebars.compile("<img {{bindAttr src=\"view.img\"}}>"),
  didInsertElement: function() {
    var member;
    member = this.get("content");
    return this.$().tooltip({
      title: "" + member.name + " - " + member.role,
      placement: "top",
      hide: 100
    });
  }
});

App.ProjectSlideView = Em.View.extend({
  tagName: "li",
  hrefBinding: 'content.uri',
  img: (function() {
    var title;
    title = get(this, 'content.title');
    title = title.replace(/\s/g, "_").toLowerCase();
    return "build/client/img/projects/" + title + ".png";
  }).property("content.title"),
  template: Em.Handlebars.compile("<a {{bindAttr href=\"view.href\" target=\"external\"}}>\n<img {{bindAttr src=\"view.img\"}}>\n</a>")
});

App.ProjectSliderView = Em.CollectionView.extend({
  tagName: 'ul',
  itemViewClass: App.ProjectSlideView,
  didInsertElement: function() {
    require('./easyslider');
    return Em.$('#slider').easySlider({
      auto: true,
      continuous: true,
      numeric: true
    });
  }
});
